[package]
name = "cxweb-browser-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
cxweb-platform.workspace = true
cxweb-codex-adapter.workspace = true
serde_json.workspace = true
thiserror.workspace = true
serde.workspace = true
cxweb-domain.workspace = true

[lints]
workspace = true
