//! Authentication/classification boundary shared by future web providers.
use crate::native::{NativeRoute, NativeTransport, unavailable};
use axum::{
    Router,
    body::Bytes,
    extract::{DefaultBodyLimit, State, WebSocketUpgrade},
    http::{HeaderMap, Method, StatusCode, Uri},
    response::{IntoResponse, Response},
    routing::any,
};
use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
use cxweb_codex_adapter::strict_json;
use serde_json::Value;
use std::{
    future::Future,
    pin::Pin,
    sync::{Arc, Mutex},
    time::Duration,
};
use tokio::sync::Notify;
use tokio_util::sync::CancellationToken;

/// This payload cannot carry transport headers, native authorization or the
/// installation capability. Its history is untrusted model input, never code.
pub struct WebRequest {
    pub payload: Value,
    pub identity: Option<crate::web_provider::WebIdentity>,
    pub compact: bool,
    pub cancellation: CancellationToken,
    pub transport: WebTransport,
}
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum WebTransport {
    Http,
    WebSocket,
}
pub type WebFuture = Pin<Box<dyn Future<Output = Response> + Send>>;
pub trait WebProvider: Send + Sync {
    /// Keep this future alive until generation and cancellation cleanup finish.
    /// Return buffered output; returning an independently generating stream is
    /// not supported by the current coordinator or disconnect drain contract.
    fn respond(&self, request: WebRequest) -> WebFuture;
    /// Validate a no-generation WebSocket warmup without touching the browser.
    fn validate_warmup(&self, _request: &WebRequest) -> Result<(), &'static str> {
        Err("E_COMPATIBILITY_UNQUALIFIED")
    }
    /// Return only entries generated by a qualified codec for this exact query.
    /// Native authorization is deliberately not available to the web provider.
    fn catalog(&self, _query: Option<&str>) -> Option<crate::catalog_proxy::OwnedCatalog> {
        None
    }
}

pub struct UnqualifiedProvider;
impl WebProvider for UnqualifiedProvider {
    fn respond(&self, _: WebRequest) -> WebFuture {
        Box::pin(async { unavailable("E_COMPATIBILITY_UNQUALIFIED") })
    }
}

#[derive(Clone)]
pub struct Gateway {
    authority: String,
    capability: String,
    native: NativeTransport,
    web: Arc<dyn WebProvider>,
    admission: Arc<WebAdmission>,
}

struct WebAdmission {
    state: Mutex<AdmissionState>,
    cancel: CancellationToken,
    drained: Notify,
}
struct AdmissionState {
    accepting: bool,
    active: usize,
    cleanup_failed: bool,
}
struct WebLease(Arc<WebAdmission>);
impl Drop for WebLease {
    fn drop(&mut self) {
        if let Ok(mut state) = self.0.state.lock() {
            if std::thread::panicking() {
                state.cleanup_failed = true;
                state.accepting = false;
                self.0.cancel.cancel();
            }
            state.active -= 1;
            if state.active == 0 {
                self.0.drained.notify_waiters();
            }
        }
    }
}
impl WebAdmission {
    fn acquire(self: &Arc<Self>) -> Option<WebLease> {
        let mut state = self.state.lock().ok()?;
        if !state.accepting {
            return None;
        }
        state.active += 1;
        Some(WebLease(self.clone()))
    }
    async fn drain(&self) -> Result<(), &'static str> {
        loop {
            let notified = self.drained.notified();
            tokio::pin!(notified);
            notified.as_mut().enable();
            {
                let state = self.state.lock().map_err(|_| "E_GATEWAY_STATE")?;
                if state.cleanup_failed {
                    return Err("E_WEB_CLEANUP_UNCONFIRMED");
                }
                if state.active == 0 {
                    return Ok(());
                }
            }
            notified.await;
        }
    }
}

impl Gateway {
    /// Both transports retain the drain lease until provider cleanup completes.
    /// Dropping this delivery future cancels work without dropping its worker.
    pub(crate) async fn dispatch_web(
        &self,
        payload: Value,
        identity: Option<crate::web_provider::WebIdentity>,
        compact: bool,
        warmup: bool,
        transport: WebTransport,
    ) -> Response {
        let Some(lease) = self.admission.acquire() else {
            return unavailable("E_WEB_DISCONNECTED");
        };
        let cancellation = self.admission.cancel.child_token();
        let _cancel_on_disconnect = cancellation.clone().drop_guard();
        let web = self.web.clone();
        let worker = tokio::spawn(async move {
            let _lease = lease;
            if cancellation.is_cancelled() {
                return unavailable("E_CANCELLED");
            }
            let request = WebRequest {
                payload,
                identity,
                compact,
                cancellation,
                transport,
            };
            if warmup {
                return match web.validate_warmup(&request) {
                    Ok(()) => crate::web_ws::warmup_response(&request.payload),
                    Err(code) => crate::web_provider::web_failure(code),
                };
            }
            web.respond(request).await
        });
        worker.await.unwrap_or_else(|_| unavailable("E_WEB_WORKER"))
    }
    pub fn new(port: u16, native: NativeTransport, web: Arc<dyn WebProvider>) -> Self {
        Self {
            authority: format!("127.0.0.1:{port}"),
            capability: URL_SAFE_NO_PAD.encode(rand::random::<[u8; 32]>()),
            native,
            web,
            admission: Arc::new(WebAdmission {
                state: Mutex::new(AdmissionState {
                    accepting: true,
                    active: 0,
                    cleanup_failed: false,
                }),
                cancel: CancellationToken::new(),
                drained: Notify::new(),
            }),
        }
    }
    pub fn base_url(&self) -> String {
        format!(
            "http://{}/wb/{}/backend-api/codex",
            self.authority, self.capability
        )
    }
    /// Only a validated private journal may restore an existing capability.
    #[cfg(windows)]
    pub(crate) fn recover_native(port: u16, capability: &str, native: NativeTransport) -> Self {
        let mut gateway = Self::new(port, native, Arc::new(UnqualifiedProvider));
        gateway.capability = capability.to_owned();
        gateway
            .admission
            .state
            .lock()
            .expect("new admission lock")
            .accepting = false;
        gateway.admission.cancel.cancel();
        gateway
    }
    /// Irreversibly reject new web work on this listener, request cancellation,
    /// and wait for admitted providers to finish cleanup. Timeout is not a drain
    /// success: keep the listener and do not remove configuration on that result.
    /// Native HTTP/WS routes remain available to clients using the old URL.
    pub async fn disconnect_web(&self, deadline: Duration) -> Result<(), &'static str> {
        self.admission
            .state
            .lock()
            .map_err(|_| "E_GATEWAY_STATE")?
            .accepting = false;
        self.admission.cancel.cancel();
        tokio::time::timeout(deadline, self.admission.drain())
            .await
            .map_err(|_| "E_WEB_DRAIN_TIMEOUT")?
    }
    pub fn router(self) -> Router {
        Router::new()
            .fallback(any(handle))
            .layer(DefaultBodyLimit::max(32 * 1024 * 1024))
            .with_state(self)
    }
}

async fn handle(
    State(gateway): State<Gateway>,
    upgrade: Result<WebSocketUpgrade, axum::extract::ws::rejection::WebSocketUpgradeRejection>,
    method: Method,
    uri: Uri,
    headers: HeaderMap,
    bytes: Bytes,
) -> Response {
    if headers.contains_key("origin")
        || headers.get_all("host").iter().count() != 1
        || headers.get("host").and_then(|h| h.to_str().ok()) != Some(&gateway.authority)
    {
        return StatusCode::FORBIDDEN.into_response();
    }
    let prefix = format!("/wb/{}/backend-api/codex/", gateway.capability);
    let legacy = format!("/wb/{}/v1/", gateway.capability);
    if method == Method::GET
        && (uri.path() == prefix.trim_end_matches('/')
            || uri.path() == legacy.trim_end_matches('/')
            || uri.path() == format!("{legacy}realtime"))
        && let Ok(upgrade) = upgrade
    {
        let route = match headers
            .get("openai-alpha")
            .and_then(|value| value.to_str().ok())
        {
            Some("quicksilver=v2") => crate::native_ws::SocketRoute::Live,
            None | Some("quicksilver=v1") => crate::native_ws::SocketRoute::Realtime,
            _ => return StatusCode::BAD_REQUEST.into_response(),
        };
        return gateway
            .native
            .upgrade(route, upgrade, uri.query(), headers, None)
            .await;
    }
    let Some(path) = uri
        .path()
        .strip_prefix(&prefix)
        .or_else(|| uri.path().strip_prefix(&legacy))
    else {
        return StatusCode::NOT_FOUND.into_response();
    };
    if method == Method::GET
        && path == "responses"
        && let Ok(upgrade) = upgrade
    {
        return gateway
            .native
            .upgrade(
                crate::native_ws::SocketRoute::Responses,
                upgrade,
                uri.query(),
                headers,
                Some(gateway.clone()),
            )
            .await;
    }
    let route = match (&method, path) {
        (&Method::GET, "models") => NativeRoute::Models,
        (&Method::POST, "responses") => NativeRoute::Responses,
        (&Method::POST, "responses/compact") => NativeRoute::Compact,
        (&Method::POST, "memories/trace_summarize") => NativeRoute::MemorySummarize,
        (&Method::POST, "alpha/search") => NativeRoute::Search,
        (&Method::POST, "images/generations") => NativeRoute::ImageGeneration,
        (&Method::POST, "images/edits") => NativeRoute::ImageEdit,
        (&Method::POST, "realtime/calls") => NativeRoute::RealtimeCall,
        // Only exact reviewed routes are admitted. Realtime and other auxiliary
        // endpoints still require separate transport qualification.
        _ => return StatusCode::NOT_FOUND.into_response(),
    };
    if matches!(route, NativeRoute::Models)
        && let Some(_lease) = gateway.admission.acquire()
        && let Some(catalog) = gateway.web.catalog(uri.query())
    {
        return crate::catalog_proxy::forward(&gateway.native, uri.query(), headers, catalog).await;
    }
    let inspected = if method == Method::POST {
        match crate::request_body::decode(&headers, bytes.clone()).await {
            Ok(decoded) => decoded,
            Err(status) => return status.into_response(),
        }
    } else {
        bytes.clone()
    };
    if matches!(route, NativeRoute::RealtimeCall) {
        // Subscription clients send JSON with a nested session; older call
        // creation also supports raw SDP. Neither is a Responses request.
        let media = headers
            .get("content-type")
            .and_then(|value| value.to_str().ok())
            .and_then(|value| value.split(';').next())
            .map(str::trim);
        match media {
            Some(value) if value.eq_ignore_ascii_case("application/sdp") => (),
            Some(value) if value.eq_ignore_ascii_case("application/json") => {
                let Ok(payload) = strict_json::parse(&inspected, 32 * 1024 * 1024) else {
                    return StatusCode::BAD_REQUEST.into_response();
                };
                let Some(session) = payload.get("session").and_then(Value::as_object) else {
                    return StatusCode::BAD_REQUEST.into_response();
                };
                if payload.get("sdp").and_then(Value::as_str).is_none() {
                    return StatusCode::BAD_REQUEST.into_response();
                }
                for model in [payload.get("model"), session.get("model")]
                    .into_iter()
                    .flatten()
                {
                    if model.is_null() {
                        continue;
                    }
                    match model.as_str() {
                        Some(model) if model.starts_with(cxweb_domain::OWNED_MODEL_PREFIX) => {
                            return unavailable("E_WEB_CAPABILITY_UNSUPPORTED");
                        }
                        Some(_) => (),
                        None => return StatusCode::BAD_REQUEST.into_response(),
                    }
                }
            }
            _ => return StatusCode::UNSUPPORTED_MEDIA_TYPE.into_response(),
        }
    } else if method == Method::POST {
        let payload = match strict_json::parse(&inspected, 32 * 1024 * 1024) {
            Ok(payload) => payload,
            Err(_) => return StatusCode::BAD_REQUEST.into_response(),
        };
        let Some(model) = payload.get("model").and_then(Value::as_str) else {
            return StatusCode::BAD_REQUEST.into_response();
        };
        let generation = matches!(route, NativeRoute::Responses | NativeRoute::Compact);
        if model.starts_with(cxweb_domain::OWNED_MODEL_PREFIX) {
            // Native-only capabilities must never turn an owned web model into
            // an authenticated native inference request or a browser tool call.
            if !generation {
                return unavailable("E_WEB_CAPABILITY_UNSUPPORTED");
            }
            if inspected.len() > 8 * 1024 * 1024 {
                return StatusCode::PAYLOAD_TOO_LARGE.into_response();
            }
            // Drop bearer-bearing transport state before entering browser code.
            let identity = crate::web_provider::WebIdentity::from_headers(&headers);
            drop(headers);
            return gateway
                .dispatch_web(
                    payload,
                    identity,
                    matches!(route, NativeRoute::Compact),
                    false,
                    WebTransport::Http,
                )
                .await;
        }
    }
    gateway
        .native
        .forward(route, uri.query(), headers, bytes)
        .await
        .unwrap_or_else(unavailable)
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::{body::Body, http::Request};
    use http_body_util::BodyExt;
    use std::sync::atomic::{AtomicUsize, Ordering};
    use tower::ServiceExt;

    struct Spy {
        calls: AtomicUsize,
    }
    impl WebProvider for Spy {
        fn respond(&self, request: WebRequest) -> WebFuture {
            self.calls.fetch_add(1, Ordering::SeqCst);
            assert!(!request.payload.to_string().contains("NATIVE_SECRET"));
            Box::pin(async { "web branch".into_response() })
        }
    }

    #[tokio::test]
    async fn native_auxiliary_routes_preserve_payload_and_never_enter_browser() {
        let received = Arc::new(AtomicUsize::new(0));
        let count = received.clone();
        let upstream = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let native =
            NativeTransport::new(format!("http://{}", upstream.local_addr().unwrap())).unwrap();
        let server = tokio::spawn(async move {
            axum::serve(
                upstream,
                Router::new().fallback(any(
                    move |method: Method, uri: Uri, headers: HeaderMap, body: Bytes| {
                        let count = count.clone();
                        async move {
                            assert_eq!(method, Method::POST);
                            assert_eq!(uri.query(), Some("client_version=0.153.4"));
                            assert_eq!(headers["authorization"], "Bearer MOCK_NATIVE_SECRET");
                            assert_eq!(headers["chatgpt-account-id"], "mock-account");
                            count.fetch_add(1, Ordering::SeqCst);
                            Response::builder()
                                .status(StatusCode::TOO_MANY_REQUESTS)
                                .header("content-type", "application/json")
                                .header("retry-after", "7")
                                .header("x-reviewed-path", uri.path())
                                .body(Body::from(body))
                                .unwrap()
                        }
                    },
                )),
            )
            .await
            .unwrap();
        });
        let spy = Arc::new(Spy {
            calls: AtomicUsize::new(0),
        });
        let gateway = Gateway::new(12345, native, spy.clone());
        // Native functions remain available after web admission is disabled.
        gateway
            .disconnect_web(Duration::from_secs(1))
            .await
            .unwrap();
        let base = gateway.base_url();
        let router = gateway.router();
        for (path, body) in [
            (
                "memories/trace_summarize",
                "{ \"model\":\"native\",\"traces\":[] }\n",
            ),
            (
                "alpha/search",
                "{\"model\":\"native\",\"input\":\"webbridge/reference in ordinary data\"}\n",
            ),
            (
                "images/generations",
                "{\"model\":\"native-image\", \"prompt\":\"fixture\"}",
            ),
            (
                "images/edits",
                "{\"model\":\"native-image\",\"images\":[], \"prompt\":\"fixture\"}",
            ),
        ] {
            let response = router
                .clone()
                .oneshot(
                    Request::builder()
                        .method("POST")
                        .uri(format!("{base}/{path}?client_version=0.153.4"))
                        .header("host", "127.0.0.1:12345")
                        .header("authorization", "Bearer MOCK_NATIVE_SECRET")
                        .header("chatgpt-account-id", "mock-account")
                        .header("content-type", "application/json")
                        .body(Body::from(body))
                        .unwrap(),
                )
                .await
                .unwrap();
            assert_eq!(response.status(), StatusCode::TOO_MANY_REQUESTS);
            assert_eq!(response.headers()["retry-after"], "7");
            assert_eq!(response.headers()["x-reviewed-path"], format!("/{path}"));
            assert_eq!(
                response.into_body().collect().await.unwrap().to_bytes(),
                body
            );
        }
        assert_eq!(received.load(Ordering::SeqCst), 4);
        assert_eq!(spy.calls.load(Ordering::SeqCst), 0);
        server.abort();
    }

    #[tokio::test]
    async fn auxiliary_owned_models_and_unreviewed_paths_never_reach_upstream() {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let native =
            NativeTransport::new(format!("http://{}", listener.local_addr().unwrap())).unwrap();
        let spy = Arc::new(Spy {
            calls: AtomicUsize::new(0),
        });
        let gateway = Gateway::new(12345, native, spy.clone());
        let base = gateway.base_url();
        let router = gateway.router();
        for path in [
            "memories/trace_summarize",
            "alpha/search",
            "images/generations",
            "images/edits",
        ] {
            let response = router
                .clone()
                .oneshot(
                    Request::builder()
                        .method("POST")
                        .uri(format!("{base}/{path}"))
                        .header("host", "127.0.0.1:12345")
                        .body(Body::from(r#"{"model":"webbridge/test"}"#))
                        .unwrap(),
                )
                .await
                .unwrap();
            assert_eq!(response.status(), StatusCode::BAD_GATEWAY);
            let error = response.into_body().collect().await.unwrap().to_bytes();
            assert!(
                std::str::from_utf8(&error)
                    .unwrap()
                    .contains("E_WEB_CAPABILITY_UNSUPPORTED")
            );
        }
        for (method, path) in [
            ("GET", "alpha/search"),
            ("POST", "alpha/search/extra"),
            ("POST", "images%2fedits"),
            ("POST", "realtime/unreviewed"),
        ] {
            let response = router
                .clone()
                .oneshot(
                    Request::builder()
                        .method(method)
                        .uri(format!("{base}/{path}"))
                        .header("host", "127.0.0.1:12345")
                        .body(Body::from("{}"))
                        .unwrap(),
                )
                .await
                .unwrap();
            assert_eq!(response.status(), StatusCode::NOT_FOUND);
        }
        assert_eq!(spy.calls.load(Ordering::SeqCst), 0);
        assert!(
            tokio::time::timeout(Duration::from_millis(50), listener.accept())
                .await
                .is_err()
        );
    }

    #[tokio::test]
    async fn realtime_call_preserves_json_sdp_and_location_without_browser_access() {
        let upstream = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let native =
            NativeTransport::new(format!("http://{}", upstream.local_addr().unwrap())).unwrap();
        let server = tokio::spawn(async move {
            axum::serve(
                upstream,
                Router::new().route(
                    "/realtime/calls",
                    any(|uri: Uri, headers: HeaderMap, bytes: Bytes| async move {
                        assert_eq!(uri.query(), Some("intent=quicksilver&architecture=avas"));
                        assert_eq!(headers["authorization"], "Bearer MOCK_NATIVE_SECRET");
                        Response::builder()
                            .status(StatusCode::CREATED)
                            .header(
                                "location",
                                "https://api.openai.com/v1/realtime/calls/fixture-call",
                            )
                            .header("content-type", headers["content-type"].clone())
                            .body(Body::from(bytes))
                            .unwrap()
                    }),
                ),
            )
            .await
            .unwrap();
        });
        let spy = Arc::new(Spy {
            calls: AtomicUsize::new(0),
        });
        let gateway = Gateway::new(12345, native, spy.clone());
        let base = gateway.base_url();
        assert!(base.contains("/backend-api"));
        gateway
            .disconnect_web(Duration::from_secs(1))
            .await
            .unwrap();
        let router = gateway.router();
        for (media, body) in [
            (
                "application/json",
                "{ \"sdp\":\"v=0\\r\\n\", \"session\":{\"model\":\"native-realtime\"}}\n",
            ),
            (
                "application/json; charset=utf-8",
                "{\"sdp\":\"v=0\",\"session\":{\"model\":null}}",
            ),
            ("application/sdp", "v=0\r\no=fixture\r\n"),
        ] {
            let response = router
                .clone()
                .oneshot(
                    Request::builder()
                        .method("POST")
                        .uri(format!(
                            "{base}/realtime/calls?intent=quicksilver&architecture=avas"
                        ))
                        .header("host", "127.0.0.1:12345")
                        .header("authorization", "Bearer MOCK_NATIVE_SECRET")
                        .header("content-type", media)
                        .body(Body::from(body))
                        .unwrap(),
                )
                .await
                .unwrap();
            assert_eq!(response.status(), StatusCode::CREATED);
            assert_eq!(
                response.headers()["location"],
                "https://api.openai.com/v1/realtime/calls/fixture-call"
            );
            assert_eq!(response.headers()["content-type"], media);
            assert_eq!(
                response.into_body().collect().await.unwrap().to_bytes(),
                body
            );
        }
        assert_eq!(spy.calls.load(Ordering::SeqCst), 0);
        server.abort();
    }

    #[tokio::test]
    async fn realtime_rejects_owned_nested_models_and_unqualified_media_before_connecting() {
        let upstream = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let native =
            NativeTransport::new(format!("http://{}", upstream.local_addr().unwrap())).unwrap();
        let gateway = Gateway::new(12345, native, Arc::new(UnqualifiedProvider));
        let base = gateway.base_url();
        let router = gateway.router();
        for (media, body, status) in [
            (
                "application/json",
                r#"{"sdp":"v=0","session":{"model":"webbridge/test"}}"#,
                StatusCode::BAD_GATEWAY,
            ),
            (
                "application/json",
                r#"{"sdp":"v=0","session":{"model":"native","model":"webbridge/test"}}"#,
                StatusCode::BAD_REQUEST,
            ),
            (
                "application/json",
                r#"{"sdp":"v=0","session":[],"model":"native"}"#,
                StatusCode::BAD_REQUEST,
            ),
            (
                "multipart/form-data; boundary=fixture",
                "fixture",
                StatusCode::UNSUPPORTED_MEDIA_TYPE,
            ),
        ] {
            let response = router
                .clone()
                .oneshot(
                    Request::builder()
                        .method("POST")
                        .uri(format!("{base}/realtime/calls"))
                        .header("host", "127.0.0.1:12345")
                        .header("content-type", media)
                        .body(Body::from(body))
                        .unwrap(),
                )
                .await
                .unwrap();
            assert_eq!(response.status(), status);
        }
        assert!(
            tokio::time::timeout(Duration::from_millis(50), upstream.accept())
                .await
                .is_err()
        );
    }

    #[tokio::test]
    async fn request_branch_never_exposes_native_authorization_to_web_provider() {
        let spy = Arc::new(Spy {
            calls: AtomicUsize::new(0),
        });
        let gateway = Gateway::new(12345, NativeTransport::subscription().unwrap(), spy.clone());
        let url = format!("{}/responses", gateway.base_url());
        let request = Request::builder()
            .method("POST")
            .uri(url)
            .header("host", "127.0.0.1:12345")
            .header("authorization", "Bearer NATIVE_SECRET")
            .body(Body::from(r#"{"model":"webbridge/test","input":"hello"}"#))
            .unwrap();
        let response = gateway.router().oneshot(request).await.unwrap();
        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            response.into_body().collect().await.unwrap().to_bytes(),
            "web branch"
        );
        assert_eq!(spy.calls.load(Ordering::SeqCst), 1);
    }

    #[tokio::test]
    async fn compressed_requests_preserve_native_bytes_and_enforce_decoded_web_limits() {
        let native_body =
            zstd::stream::encode_all(&br#"{"model":"native","input":"fixture"}"#[..], 1).unwrap();
        let expected = native_body.clone();
        let received = Arc::new(AtomicUsize::new(0));
        let counter = received.clone();
        let upstream = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let native =
            NativeTransport::new(format!("http://{}", upstream.local_addr().unwrap())).unwrap();
        let server = tokio::spawn(async move {
            axum::serve(
                upstream,
                Router::new().route(
                    "/responses",
                    any(move |headers: HeaderMap, bytes: Bytes| {
                        let expected = expected.clone();
                        let counter = counter.clone();
                        async move {
                            assert_eq!(bytes.as_ref(), expected.as_slice());
                            assert_eq!(headers["content-encoding"], "zstd");
                            assert_eq!(headers["authorization"], "Bearer MOCK_NATIVE_SECRET");
                            counter.fetch_add(1, Ordering::SeqCst);
                            Response::builder()
                                .header("content-encoding", "zstd")
                                .body(Body::from(bytes))
                                .unwrap()
                        }
                    }),
                ),
            )
            .await
            .unwrap();
        });
        let spy = Arc::new(Spy {
            calls: AtomicUsize::new(0),
        });
        let gateway = Gateway::new(12345, native, spy.clone());
        let base = gateway.base_url();
        let router = gateway.router();
        let request = |body: Vec<u8>| {
            Request::builder()
                .method("POST")
                .uri(format!("{base}/responses"))
                .header("host", "127.0.0.1:12345")
                .header("content-encoding", "zstd")
                .header("content-type", "application/json")
                .header("authorization", "Bearer MOCK_NATIVE_SECRET")
                .body(Body::from(body))
                .unwrap()
        };
        let response = router
            .clone()
            .oneshot(request(native_body.clone()))
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(response.headers()["content-encoding"], "zstd");
        assert_eq!(
            response
                .into_body()
                .collect()
                .await
                .unwrap()
                .to_bytes()
                .as_ref(),
            native_body.as_slice()
        );
        let web =
            zstd::stream::encode_all(&br#"{"model":"webbridge/test","input":"fixture"}"#[..], 1)
                .unwrap();
        assert_eq!(
            router.clone().oneshot(request(web)).await.unwrap().status(),
            StatusCode::OK
        );
        let duplicate =
            zstd::stream::encode_all(&br#"{"model":"native","model":"webbridge/test"}"#[..], 1)
                .unwrap();
        assert_eq!(
            router
                .clone()
                .oneshot(request(duplicate))
                .await
                .unwrap()
                .status(),
            StatusCode::BAD_REQUEST
        );
        let large =
            serde_json::json!({"model":"webbridge/test","input":"x".repeat(8 * 1024 * 1024)})
                .to_string();
        let large = zstd::stream::encode_all(large.as_bytes(), 1).unwrap();
        assert!(large.len() < 8192);
        assert_eq!(
            router.oneshot(request(large)).await.unwrap().status(),
            StatusCode::PAYLOAD_TOO_LARGE
        );
        assert_eq!(received.load(Ordering::SeqCst), 1);
        assert_eq!(spy.calls.load(Ordering::SeqCst), 1);
        server.abort();
    }

    #[tokio::test]
    async fn malformed_request_cannot_choose_a_different_route_via_duplicate_model() {
        let spy = Arc::new(Spy {
            calls: AtomicUsize::new(0),
        });
        let gateway = Gateway::new(12345, NativeTransport::subscription().unwrap(), spy.clone());
        let url = format!("{}/responses", gateway.base_url());
        let request = Request::builder()
            .method("POST")
            .uri(url)
            .header("host", "127.0.0.1:12345")
            .body(Body::from(r#"{"model":"native","model":"webbridge/test"}"#))
            .unwrap();
        assert_eq!(
            gateway.router().oneshot(request).await.unwrap().status(),
            StatusCode::BAD_REQUEST
        );
        assert_eq!(spy.calls.load(Ordering::SeqCst), 0);
    }

    #[tokio::test]
    async fn catalog_augmentation_requires_an_explicit_qualified_provider_snapshot() {
        struct CatalogOnly;
        impl WebProvider for CatalogOnly {
            fn respond(&self, _: WebRequest) -> WebFuture {
                panic!("catalog must not generate");
            }
            fn catalog(&self, query: Option<&str>) -> Option<crate::catalog_proxy::OwnedCatalog> {
                (query == Some("client_version=test-codec")).then(|| {
                    crate::catalog_proxy::OwnedCatalog {
                        codec: "test-codec".into(),
                        web_scope: "synthetic-scope".into(),
                        generation: 1,
                        entries: vec![cxweb_codex_adapter::catalog::synthetic_model()],
                    }
                })
            }
        }
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        let server = tokio::spawn(async move {
            axum::serve(
                listener,
                Router::new().route(
                    "/models",
                    axum::routing::get(|| async {
                        axum::Json(serde_json::json!({"models":[{"slug":"native"}]}))
                    }),
                ),
            )
            .await
            .unwrap();
        });
        let gateway = Gateway::new(
            12345,
            NativeTransport::new(format!("http://{address}")).unwrap(),
            Arc::new(CatalogOnly),
        );
        for (query, count, disconnect) in [
            ("test-codec", 2, false),
            ("unknown-codec", 1, false),
            ("test-codec", 1, true),
        ] {
            if disconnect {
                gateway
                    .disconnect_web(Duration::from_secs(1))
                    .await
                    .unwrap();
            }
            let response = gateway
                .clone()
                .router()
                .oneshot(
                    Request::builder()
                        .uri(format!(
                            "{}/models?client_version={query}",
                            gateway.base_url()
                        ))
                        .header("host", "127.0.0.1:12345")
                        .body(Body::empty())
                        .unwrap(),
                )
                .await
                .unwrap();
            assert_eq!(response.status(), StatusCode::OK);
            let body = response.into_body().collect().await.unwrap().to_bytes();
            let catalog: Value = serde_json::from_slice(&body).unwrap();
            assert_eq!(catalog["models"].as_array().unwrap().len(), count);
        }
        server.abort();
    }

    struct WaitingProvider {
        started: Arc<Notify>,
        cancelled: Arc<Notify>,
        cleanup: Arc<tokio::sync::Semaphore>,
    }
    #[tokio::test]
    async fn provider_panic_does_not_certify_successful_cleanup() {
        struct Panicking;
        impl WebProvider for Panicking {
            fn respond(&self, _: WebRequest) -> WebFuture {
                Box::pin(async { panic!("synthetic worker failure") })
            }
        }
        let gateway = Gateway::new(
            12345,
            NativeTransport::subscription().unwrap(),
            Arc::new(Panicking),
        );
        let response = gateway
            .clone()
            .router()
            .oneshot(owned_request(&gateway.base_url()))
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::BAD_GATEWAY);
        assert_eq!(
            gateway.disconnect_web(Duration::from_secs(1)).await,
            Err("E_WEB_CLEANUP_UNCONFIRMED")
        );
        let response = gateway
            .clone()
            .router()
            .oneshot(owned_request(&gateway.base_url()))
            .await
            .unwrap();
        let bytes = response.into_body().collect().await.unwrap().to_bytes();
        assert!(
            std::str::from_utf8(&bytes)
                .unwrap()
                .contains("E_WEB_DISCONNECTED")
        );
    }
    impl WebProvider for WaitingProvider {
        fn respond(&self, request: WebRequest) -> WebFuture {
            let (started, cancelled, cleanup) = (
                self.started.clone(),
                self.cancelled.clone(),
                self.cleanup.clone(),
            );
            Box::pin(async move {
                started.notify_one();
                request.cancellation.cancelled().await;
                cancelled.notify_one();
                let _permit = cleanup.acquire().await.unwrap();
                unavailable("E_CANCELLED")
            })
        }
    }
    fn owned_request(base: &str) -> Request<Body> {
        Request::builder()
            .method("POST")
            .uri(format!("{base}/responses"))
            .header("host", "127.0.0.1:12345")
            .body(Body::from(r#"{"model":"webbridge/test","input":"hello"}"#))
            .unwrap()
    }

    #[tokio::test]
    async fn disconnect_and_client_drop_wait_for_actual_provider_cleanup() {
        for client_drop in [false, true] {
            let started = Arc::new(Notify::new());
            let cancelled = Arc::new(Notify::new());
            let cleanup = Arc::new(tokio::sync::Semaphore::new(0));
            let gateway = Gateway::new(
                12345,
                NativeTransport::subscription().unwrap(),
                Arc::new(WaitingProvider {
                    started: started.clone(),
                    cancelled: cancelled.clone(),
                    cleanup: cleanup.clone(),
                }),
            );
            let request = owned_request(&gateway.base_url());
            let router = gateway.clone().router();
            let pending = tokio::spawn(async move { router.oneshot(request).await.unwrap() });
            tokio::time::timeout(Duration::from_secs(1), started.notified())
                .await
                .unwrap();
            if client_drop {
                pending.abort();
                tokio::time::timeout(Duration::from_secs(1), cancelled.notified())
                    .await
                    .unwrap();
            }
            assert_eq!(
                gateway.disconnect_web(Duration::from_millis(20)).await,
                Err("E_WEB_DRAIN_TIMEOUT")
            );
            if !client_drop {
                tokio::time::timeout(Duration::from_secs(1), cancelled.notified())
                    .await
                    .unwrap();
            }
            let rejected = gateway
                .clone()
                .router()
                .oneshot(owned_request(&gateway.base_url()))
                .await
                .unwrap();
            let body = rejected.into_body().collect().await.unwrap().to_bytes();
            assert!(
                std::str::from_utf8(&body)
                    .unwrap()
                    .contains("E_WEB_DISCONNECTED")
            );
            cleanup.add_permits(1);
            gateway
                .disconnect_web(Duration::from_secs(1))
                .await
                .unwrap();
            if !client_drop {
                assert_eq!(pending.await.unwrap().status(), StatusCode::BAD_GATEWAY);
            }
            gateway
                .disconnect_web(Duration::from_secs(1))
                .await
                .unwrap();
        }
    }

    #[tokio::test]
    async fn disconnected_listener_forwards_native_http_but_rejects_owned_responses_and_compaction()
    {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        let native_calls = Arc::new(AtomicUsize::new(0));
        let calls = native_calls.clone();
        let server = tokio::spawn(async move {
            axum::serve(
                listener,
                Router::new().fallback(any(move |headers: HeaderMap, bytes: Bytes| {
                    let calls = calls.clone();
                    async move {
                        assert_eq!(headers["authorization"], "Bearer SYNTHETIC_NATIVE");
                        calls.fetch_add(1, Ordering::SeqCst);
                        (StatusCode::ACCEPTED, bytes)
                    }
                })),
            )
            .await
            .unwrap();
        });
        let spy = Arc::new(Spy {
            calls: AtomicUsize::new(0),
        });
        let gateway = Gateway::new(
            12345,
            NativeTransport::new(format!("http://{address}")).unwrap(),
            spy.clone(),
        );
        gateway
            .disconnect_web(Duration::from_secs(1))
            .await
            .unwrap();
        for path in ["responses", "responses/compact"] {
            for model in ["native", "webbridge/test"] {
                let body = format!("{{\"model\":\"{model}\",\"input\":\"literal input\"}}");
                let response = gateway
                    .clone()
                    .router()
                    .oneshot(
                        Request::builder()
                            .method("POST")
                            .uri(format!("{}/{path}", gateway.base_url()))
                            .header("host", "127.0.0.1:12345")
                            .header("authorization", "Bearer SYNTHETIC_NATIVE")
                            .body(Body::from(body.clone()))
                            .unwrap(),
                    )
                    .await
                    .unwrap();
                if model == "native" {
                    assert_eq!(response.status(), StatusCode::ACCEPTED);
                    assert_eq!(
                        response.into_body().collect().await.unwrap().to_bytes(),
                        body
                    );
                } else {
                    assert_eq!(response.status(), StatusCode::BAD_GATEWAY);
                    let bytes = response.into_body().collect().await.unwrap().to_bytes();
                    assert!(
                        std::str::from_utf8(&bytes)
                            .unwrap()
                            .contains("E_WEB_DISCONNECTED")
                    );
                }
            }
        }
        assert_eq!(native_calls.load(Ordering::SeqCst), 2);
        assert_eq!(spy.calls.load(Ordering::SeqCst), 0);
        server.abort();
    }
}
