[package]
name = "cxweb"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cxweb-codex-adapter.workspace = true
cxweb-runtime.workspace = true
cxweb-browser-adapter.workspace = true
cxweb-platform.workspace = true
clap.workspace = true
tokio.workspace = true
serde_json.workspace = true
axum.workspace = true

[lints]
workspace = true
